### ISSUE TITLE
bad entropy default value

### ISSUE THREAD

**Issue by bnjbvr** [espadrine/passphrase#1]
if i call passphrase with an entropy of 0, the entropy will be replaced by 64, which isn't what I want.
please replace `!entropy` by `typeof entropy === 'undefined'`

**Comment by espadrine** [comment]
Did you mean `entropy == null`?

**Comment by espadrine** [comment]
I'm fairly sure a zero entropy password has no length, so the use is limited. In fact, the entropy that is fed is a lower bound, so the result may actually be a (weak) password.

**Comment by bnjbvr** [comment]
No, I didn't mean `entropy == null`, which will trigger implicit coercions (null == undefined, and `entropy` is set to undefined). Really, the best way to test this is `typeof entropy === 'undefined'`, meaning "the argument isn't given":

```
passphrase(); // entropy is set to undefined
```

If you mean different semantics, like being able to pass either a number or null, then it's fine.
Anyways, just trolling :P
