### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by mrAl-x** [espadrine/passphrase#3]
I'm trying to use this to generate a passphrase in a React app but I'm getting a "TypeError: fs.readFileSync is not a function" 🤔 

![Screenshot 2019-06-17 at 20 47 26](https://user-images.githubusercontent.com/4906508/59632032-2586be00-9141-11e9-95b3-7f2ebdbc2d4d.png)

**Comment by espadrine** [comment]
Hi! The main intended target is Node.js server-side. It is possible to tweak it to support browser environments, but I have not done that yet.

**Comment by espadrine** [comment]
Fixed by 26a3bc8d6799df3acefecdd91b2e1a3a49c3d495.
